language: node_js
node_js:
  - "8" 
services:
  - postgresql
addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d travis_ci_test

script:
  - npm test